### ISSUE TITLE
demo质量太差！！！你是在自嗨吗？java.lang.NoClassDefFoundError: com/alipay/sofa/ark/api/ArkConfigs

### ISSUE THREAD

**Issue by yupd** [sofastack-guides/sofa-ark-class-isolation#4]
# java -jar sofa-ark-class-isolation-0.0.1-SNAPSHOT-ark-executable.jar
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/alipay/sofa/ark/api/ArkConfigs
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:42)
        at com.alipay.sofa.ark.bootstrap.ArkLauncher.main(ArkLauncher.java:35)
Caused by: java.lang.ClassNotFoundException: com.alipay.sofa.ark.api.ArkConfigs
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 2 more
```

**Comment by yuanyuancin** [comment]
所以是哪个demo呢？

**Comment by yuanyuancin** [comment]
@lvjing2

**Comment by yuanyuancin** [comment]
检查下是否缺少sofa-ark-api依赖
